[project]
name = "ciri-copilot"
version = "0.1.0"
description = "Ciri Copilot CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.2.7",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.7",
    "langchain-openai>=1.1.7",
    "langgraph>=1.0.7",
    "openai>=2.15.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.0.0",
    "deepagents>=0.3.8",
    "crawl4ai>=0.8.0",
    "browser-use>=0.11.5",
    "duckduckgo-search>=8.1.1",
    "langchain-unstructured>=1.0.1",
    "langchain-mcp-adapters>=0.2.1",
    "sqlite-vec>=0.1.6",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "sqlalchemy>=2.0.46",
    "langchain-huggingface>=1.2.0",
    "pyyaml>=6.0.3",
    "sentence-transformers>=5.2.2",
    "ddgs>=9.10.0",
]

[project.optional-dependencies]
dev = [
    "pyinstaller>=6.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.scripts]
ciri = "src.__main__:main"
